image: node:8.11.2
   
stages:
  - build
  - test
  - quality

build_job:
  stage: build
  script:
#    - export NODE_PATH=/usr/bin/tsc:/usr/bin/tsserver
     - npm install
     

test_job:
  stage: test
  script:
     - npm install
     - npm run test
     - npm run test:e2e
   
quality_job:
    stage: quality
    services:
        - primetoninc/jdk:1.7
    script:     
     - npm install
     - npm run test:cov
     - wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.1.0.1141-linux.zip
     - apt-get update
     - apt-get install unzip
     - apt-get install -y jq
     - unzip sonar-scanner-cli-3.1.0.1141-linux.zip
     - ./sonar-scanner-3.1.0.1141-linux/bin/sonar-scanner
