/*
	VERSÃO DO DESENVOLVIMENTO DO BANCO: 2.1.3
*/

DROP TABLE GoogleTransit.dbo.estimativa
go

DROP TABLE GoogleTransit.dbo.historico
go

DROP TABLE GoogleTransit.dbo.viagem
go

DROP TABLE GoogleTransit.dbo.itinerario_ponto
go

DROP TABLE GoogleTransit.dbo.ponto
go

DROP TABLE GoogleTransit.dbo.feriado
go

DROP TABLE GoogleTransit.dbo.contato
go

DROP TABLE GoogleTransit.dbo.pontogeografico
go

DROP TABLE GoogleTransit.dbo.itinerario
go

DROP TABLE GoogleTransit.dbo.linha_tarifa_vigencia
go

DROP TABLE GoogleTransit.dbo.linha
go

DROP TABLE GoogleTransit.dbo.tarifa
go

DROP TABLE GoogleTransit.dbo.vigencia
go

DROP TABLE GoogleTransit.dbo.agencia
go

DROP TABLE GoogleTransit.dbo.VeiculoXPontos
go